name: Build and Release

on:
  push:
    tags:
      - 't*'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  apk-debug:
      name: Generate Debug APK
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
    
        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: "21"
    
        - name: Set execution flag for gradlew
          run: chmod +x gradlew
    
        - name: Setup Android SDK
          uses: android-actions/setup-android@v4
          with:
            packages: platform-tools
    
        - name: Install Android Build Tools
          run: sdkmanager "build-tools;29.0.3"
    
        - name: Run unit tests
          run: bash ./gradlew :common:desktopTest --stacktrace
    
        - name: Build Debug APK
          run: bash ./gradlew assembleDebug --stacktrace
    
        - name: Upload APK Artifact
          uses: actions/upload-artifact@v4
          with:
            name: debug-apk
            path: android/build/outputs/apk/debug/*.apk
